image: busybox

stages:
  - pages
#
pages:
  stage: pages
  image: docker
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose -f server/build.yml up
    - echo "The site will be deployed to $CI_PAGES_URL"
    - echo $CI_COMMIT_TAG
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG != null
    ##
