version: "3.9"

services:
  docbuilder:
    container_name: docbuilder
    build: .
    working_dir: /usr/src/app
    command: npm run build
    user: "root"
    volumes:
      - "../content:/usr/src/app/content"
      - "../assets:/usr/src/app/assets"
      - "./config:/usr/src/app/config"
      - "../docs:/usr/src/app/public:rw"
      - "./netlify.toml:/usr/src/app/netlify.toml"
      - "./package.json:/usr/src/app/package.json"
