apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-docserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://192.168.1.7/gitlab/protobox1/docserver.git
    targetRevision: CD
    path: factory/CD/base
  destination: 
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    #
    # automated:
    #   selfHeal: true
    #   prune: true